tenant_names: "calvisitor"
session_secret: "ykkgrpzyztwcizodehyhncoqotlrvyexkvekqphfwugdezlqiimjupigdoszsnxnmrgkijywyzwrpcnndubhxzfjsrfadoiyjwhpbbhmnerbmszglssdyhnpamtutebm"
attr_encrypted_key: "jmrxpjdhblvdshkkkxqdfpiudixmulds"
STRIPE_KEY: "pk_test_51IJ4KbLDn3D11BiPJcJoxR5sjCdqx0SbkmseKXaOgSlyD2NE7UPsfHpTDUCcnMxtfKJRBrRkGWqFIoi7PWgwEs8B00mkhWnuxq"
STRIPE_SECRET: "sk_test_51IJ4KbLDn3D11BiPlgHhOlfCIekx5pvcCTH5OEM3xI1GpVPkoRwif1MgQRjFMvRng0WfECJQpi4VtGnvGwgM54MU00vvvUCimA"
SENDGRID_KEY: "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"
