# Be sure to restart your server when you modify this file.

# Rails >=4 requires this file to at least contain secret_key_base, but
# we use Figaro to manage all secrets in application.yml, so just
# copy those values here for DRYness.
# (That also makes it safe to version this file.)

development:
  secret_key_base: <%= Figaro.env.session_secret! %>

test:
  secret_key_base: <%= Figaro.env.session_secret! %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= Figaro.env.session_secret! %>


